# Generated by Django 5.0.7 on 2024-08-28 14:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_locationcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(django.db.models.functions.text.Lower('name'), models.F('latitude'), models.F('longitude'), name='location_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('latitude'), models.F('longitude'), name='unique_location'),
        ),
    ]
